DROP TABLE messages;

CREATE TABLE messages(
	id SERIAL PRIMARY KEY,
	msg TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM messages;

SELECT * FROM messages ORDER BY id DESC LIMIT 10;

INSERT INTO messages(msg) VALUES('hi owo');
INSERT INTO messages(msg) VALUES('hello :3');